In [1]:
pip install tweepy

Requirement already satisfied: tweepy in c:\users\brandedhustler\anaconda3\lib\site-packages (4.10.0)
Requirement already satisfied: oauthlib<4,>=3.2.0 in c:\users\brandedhustler\anaconda3\lib\site-packages (from tweepy) (3.2.0)
Requirement already satisfied: requests<3,>=2.27.0 in c:\users\brandedhustler\anaconda3\lib\site-packages (from tweepy) (2.28.1)
Requirement already satisfied: requests-oauthlib<2,>=1.2.0 in c:\users\brandedhustler\anaconda3\lib\site-packages (from tweepy) (1.3.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\brandedhustler\anaconda3\lib\site-packages (from requests<3,>=2.27.0->tweepy) (3.2)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\brandedhustler\anaconda3\lib\site-packages (from requests<3,>=2.27.0->tweepy) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\brandedhustler\anaconda3\lib\site-packages (from requests<3,>=2.27.0->tweepy) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\brandedhustler\anaconda3\lib\site-packages (from requests<3,>=2.27.0->tweepy) (1.26.7)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import tweepy as tw
# your Twitter API key and API secret
my_api_key = "OzXfAupquMV2xDl7AYaMbVvdN"
my_api_secret = "bQLoBJhEm5sVsT51tuTn9HJxi4FP3qCbX8znxpim0n8uI46jOB"
# authenticate
auth = tw.OAuthHandler(my_api_key, my_api_secret)
api = tw.API(auth, wait_on_rate_limit=True)

In [2]:
search_query = "Messi and Neymar -filter:tweets"

In [3]:

tweets = tw.Cursor(api.search_tweets,
              q=search_query,
              lang="en",
              since="2022-08-14").items(1000)

tweets_copy = []
for tweet in tweets:
    tweets_copy.append(tweet)
    
print("Total Tweets fetched:", len(tweets_copy))

Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since
Unexpected parameter: since

Total Tweets fetched: 1000

In [6]:
import pandas as pd
# intialize the dataframe
tweets_df = pd.DataFrame()
# populate the dataframe
for tweet in tweets_copy:
    hashtags = []
    try:
        for hashtag in tweet.entities["hashtags"]:
            hashtags.append(hashtag["text"])
        text = api.get_status(id=tweet.id, tweet_mode='extended').full_text
    except:
        pass
    tweets_df = tweets_df.append(pd.DataFrame({'User_ID': tweet.user.id, 
                                               'user_name': tweet.user.name, 
#                                                'Profile_image': tweet.user.profile_image,
#                                                'Bio': tweet.user.Bio,
#                                                'Tweet_ID': tweet.user.tweet_id,
#                                                'Tweet_language': tweet.user.language,
                                               'user_location': tweet.user.location,\
                                               'user_description': tweet.user.description,
                                               'user_verified': tweet.user.verified,
                                               'Tweet_date': tweet.created_at,
                                               'Tweet_text': text, 
                                               'hashtags': [hashtags if hashtags else None],
                                               'source': tweet.source}))
    tweets_df = tweets_df.reset_index(drop=True)
# show the dataframe
tweets_df.head()

C:\Users\BRANDE~1\AppData\Local\Temp/ipykernel_12400/2766399989.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tweets_df = tweets_df.append(pd.DataFrame({'User_ID': tweet.user.id,
Rate limit reached. Sleeping for: 76

,User_ID,user_name,user_location,user_description,user_verified,Tweet_date,Tweet_text,hashtags,source
0,1243182739,Sirnucy,"Abuja , Nigeria",Architect... Special Design. Conventional thin...,False,2022-08-15 10:30:39+00:00,@Zeko_Penguin @Creeze10_ @Lionel30i That's muc...,None,Twitter for Android
1,794460474272317440,Champions Of The WorldüèÜ,RN4L‚ùóÔ∏è,@Chelseafc,False,2022-08-15 10:30:38+00:00,I need Mbatty to go Madrid so Messi and Neymar...,None,Twitter for iPhone
2,1382670869336633344,JIMüá¨üá≠üòá,,@sarkodie @cristiano,False,2022-08-15 10:30:09+00:00,RT @the_marcoli_boy: Kylian Mbappe is currentl...,None,Twitter for Android
3,3002958059,Anokye twi bible üëëüíú,"Kumasi, Ghana",Home of champions ‚úåü•Ç‚ù§,False,2022-08-15 10:30:06+00:00,@SemperFiMessi You are all fuming this bcos ua...,None,Twitter for Android
4,422738750,Darius Tanz,lagos,Money can't buy you happiness but atleast you ...,False,2022-08-15 10:30:03+00:00,"RT @Letter_to_Jack: Mbappe is doing too much, ...",None,Twitter Web App

In [7]:
tweets_df.head(5)

,User_ID,user_name,user_location,user_description,user_verified,Tweet_date,Tweet_text,hashtags,source
0,1243182739,Sirnucy,"Abuja , Nigeria",Architect... Special Design. Conventional thin...,False,2022-08-15 10:30:39+00:00,@Zeko_Penguin @Creeze10_ @Lionel30i That's muc...,None,Twitter for Android
1,794460474272317440,Champions Of The WorldüèÜ,RN4L‚ùóÔ∏è,@Chelseafc,False,2022-08-15 10:30:38+00:00,I need Mbatty to go Madrid so Messi and Neymar...,None,Twitter for iPhone
2,1382670869336633344,JIMüá¨üá≠üòá,,@sarkodie @cristiano,False,2022-08-15 10:30:09+00:00,RT @the_marcoli_boy: Kylian Mbappe is currentl...,None,Twitter for Android
3,3002958059,Anokye twi bible üëëüíú,"Kumasi, Ghana",Home of champions ‚úåü•Ç‚ù§,False,2022-08-15 10:30:06+00:00,@SemperFiMessi You are all fuming this bcos ua...,None,Twitter for Android
4,422738750,Darius Tanz,lagos,Money can't buy you happiness but atleast you ...,False,2022-08-15 10:30:03+00:00,"RT @Letter_to_Jack: Mbappe is doing too much, ...",None,Twitter Web App

In [8]:
tweets_df.to_csv('noble.csv')

In [9]:
noble = pd.read_csv('noble.csv')
noble.head(5)

,Unnamed: 0,User_ID,user_name,user_location,user_description,user_verified,Tweet_date,Tweet_text,hashtags,source
0,0,1243182739,Sirnucy,"Abuja , Nigeria",Architect... Special Design. Conventional thin...,False,2022-08-15 10:30:39+00:00,@Zeko_Penguin @Creeze10_ @Lionel30i That's muc...,NaN,Twitter for Android
1,1,794460474272317440,Champions Of The WorldüèÜ,RN4L‚ùóÔ∏è,@Chelseafc,False,2022-08-15 10:30:38+00:00,I need Mbatty to go Madrid so Messi and Neymar...,NaN,Twitter for iPhone
2,2,1382670869336633344,JIMüá¨üá≠üòá,NaN,@sarkodie @cristiano,False,2022-08-15 10:30:09+00:00,RT @the_marcoli_boy: Kylian Mbappe is currentl...,NaN,Twitter for Android
3,3,3002958059,Anokye twi bible üëëüíú,"Kumasi, Ghana",Home of champions ‚úåü•Ç‚ù§,False,2022-08-15 10:30:06+00:00,@SemperFiMessi You are all fuming this bcos ua...,NaN,Twitter for Android
4,4,422738750,Darius Tanz,lagos,Money can't buy you happiness but atleast you ...,False,2022-08-15 10:30:03+00:00,"RT @Letter_to_Jack: Mbappe is doing too much, ...",NaN,Twitter Web App

In [ ]:
noble.info()

In [ ]:
noble.sum(axis=1)

In [ ]:
df = pd.DataFrame(noble,columns=['Tweet_language','Tweet_text'])
print (df)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.manifold import TSNE
grid_params = {'n_components' : list(range(5,10))}
# LDA model
lda = LatentDirichletAllocation()
lda_model = GridSearchCV(lda,param_grid=grid_params)
lda_model.fit(speech_df)
# Estimators for LDA model
lda_model1 = lda_model.best_estimator_
print("Best LDA model's params" , lda_model.best_params_)
print("Best log likelihood Score for the LDA model",lda_model.best_score_)

In [15]:
df = pd.read_csv('noble.csv')
df

,Unnamed: 0,User_ID,user_name,user_location,user_description,user_verified,Tweet_date,Tweet_text,hashtags,source
0,0,1243182739,Sirnucy,"Abuja , Nigeria",Architect... Special Design. Conventional thin...,False,2022-08-15 10:30:39+00:00,@Zeko_Penguin @Creeze10_ @Lionel30i That's muc...,NaN,Twitter for Android
1,1,794460474272317440,Champions Of The WorldüèÜ,RN4L‚ùóÔ∏è,@Chelseafc,False,2022-08-15 10:30:38+00:00,I need Mbatty to go Madrid so Messi and Neymar...,NaN,Twitter for iPhone
2,2,1382670869336633344,JIMüá¨üá≠üòá,NaN,@sarkodie @cristiano,False,2022-08-15 10:30:09+00:00,RT @the_marcoli_boy: Kylian Mbappe is currentl...,NaN,Twitter for Android
3,3,3002958059,Anokye twi bible üëëüíú,"Kumasi, Ghana",Home of champions ‚úåü•Ç‚ù§,False,2022-08-15 10:30:06+00:00,@SemperFiMessi You are all fuming this bcos ua...,NaN,Twitter for Android
4,4,422738750,Darius Tanz,lagos,Money can't buy you happiness but atleast you ...,False,2022-08-15 10:30:03+00:00,"RT @Letter_to_Jack: Mbappe is doing too much, ...",NaN,Twitter Web App
...,...,...,...,...,...,...,...,...,...,...
995,995,2413836731,üÖò üÖêüÖú ÿπÿ®ÿØ ÿßŸÑÿ±ÿ≤ÿßŸÇ ‚Ñ¢,On My Way To Jannah,"Always, be open to both sides (there's always ...",False,2022-08-15 09:30:31+00:00,"RT @Letter_to_Jack: Mbappe is doing too much, ...",NaN,Twitter for Android
996,996,2915198523,Sir David Onyemaizuü¶ç,Lagos,Nigerian Writer/Ghostwriter/Novelist/Pianist/H...,False,2022-08-15 09:30:26+00:00,RT @evv821: Mbappe is hilarious man. When Mess...,NaN,Twitter for Android
997,997,1530477387099648001,Gyimii HeadquartersüòÇ‚ÄºÔ∏è,Heaven,Gyimii In Its HighestüôÇGod and Fooling is The P...,False,2022-08-15 09:30:13+00:00,"RT @aliswelgod: This Mbappe, Messi and Neymar ...",NaN,Twitter for iPhone
998,998,972778475424796672,Mayback,"Tema, Ghana",God Got Us‚úä || @Realmadrid || @Cristianoüêê || @...,False,2022-08-15 09:30:09+00:00,RT @__McJohnathan: Mbappe wants to be the main...,NaN,Twitter for iPhone
999,999,507736530,kofi Bekoeüëå,Ghana,social worker| humanitarian #IStandfortheJesus...,False,2022-08-15 09:29:55+00:00,RT @notthisstime: üòÇ üòÇ Hakimi saw that Messi &a...,NaN,Twitter for iPhone

In [16]:
doc= df.to_list('Tweet_text').tolist()
doc

AttributeError: 'DataFrame' object has no attribute 'to_list'

In [ ]:
import nltk
nltk.download('stopwords')

In [ ]:
from nltk.corpus import stopwords

stops = set(stopwords.words('english'))

print(stops)

In [ ]:
myTexts = [[word for word in document.split() if word not in stops]
         for document in doc]

myTexts

In [ ]:
myFrequency = defaultdict(int)
for text in myTexts:
    for token in text:
        myFrequency[token] += 1

myTexts = [[token for token in text if myFrequency[token] > 1]
         for text in myTexts]

In [ ]:
bigram = Phrases(myTexts, min_count=20)
for idx in range(len(myTexts)):
    for token in bigram[myTexts[idx]]:
        if '_' in token:
            # Token is a bigram, add to document.
            myTexts[idx].append(token)

In [ ]:
dictionary = corpora.Dictionary(myTexts)

# Filter out words that occur less than X documents, 
# or more than X% of the documents.
dictionary.filter_extremes(no_below=2, no_above=0.1)

# Create the corpus.  This is a Term Frequency 
# or Bag of Words representation.
corpus = [dictionary.doc2bow(text) for text in myTexts]

print(f'Number of unique tokens: {len(dictionary)}')
print(f'Number of documents: {len(corpus)}')

In [ ]:
NUM_TOPICS = 10
chunksize = 2000
passes = 6
iterations = 100
eval_every = 1
temp = dictionary[0]
id2word = dictionary.id2token

model = LdaModel(
    corpus=corpus,
    id2word=id2word,
    chunksize=chunksize,
    alpha='auto',
    eta='auto',
    iterations=iterations,
    num_topics=NUM_TOPICS,
    passes=passes,
    eval_every=eval_every
)

In [ ]:
def compute_coherence_values(dictionary, corpus, texts, 
                             cohere, limit, start=2, step=2):

    coherence_values = []

    for num_topics in range(start, limit, step):
        model = LdaModel(corpus=corpus, 
                         id2word=dictionary, 
                         num_topics=num_topics,
                         chunksize=chunksize,
                         alpha='auto',
                         eta='auto',
                         iterations=iterations,
                         passes=passes,
                         eval_every=eval_every,
                         random_state=42,)
        coherencemodel = CoherenceModel(model=model, 
                                        texts=texts, 
                                        dictionary=dictionary, 
                                        coherence=cohere)
        coherence_values.append(coherencemodel.get_coherence())

    return coherence_values

In [ ]:
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.DEBUG)

In [ ]:
limit=50
start=2
step=2

In [ ]:
coherence_values = compute_coherence_values(dictionary=dictionary,
                                            corpus=corpus,
                                            texts=myTexts,
                                            cohere='c_v',
                                            start=start,
                                            limit=limit,
                                            step=step)

In [ ]:
coherence_values = compute_coherence_values(dictionary=dictionary,
                                            corpus=corpus,
                                            texts=myTexts,
                                            cohere='c_v',
                                            start=start,
                                            limit=limit,
                                            step=step)

In [ ]:
temp = dictionary[0]
id2word = dictionary.id2token

model = LdaModel(
    corpus=corpus,
    id2word=id2word,
    chunksize=2000,
    alpha='auto',
    eta='auto',
    iterations=100,
    num_topics=2,
    passes=10,
    eval_every=None)

In [ ]:
pyLDAvis.enable_notebook()

# feed the LDA model into the pyLDAvis instance
lda_viz = gensimvis.prepare(model, corpus, dictionary, sort_topics=True)

pyLDAvis.display(lda_viz)